general.import = ["~/.config/alacritty/dracula.toml"]

[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0
offset = { x = 0, y = 4 }

[mouse]
hide_when_typing = true
