general.import = ["~/.config/alacritty/dracula.toml"]

[window]
padding = { x = 4, y = 4 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 16.0
offset = { x = 0, y = 4 }
