unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind c new-window -c "#{pane_current_path}"

set -g base-index 1
set -g history-limit 10000
set -a terminal-features 'xterm-256color:RGB'
setw -g mode-keys vi
setw -g mode-style 'fg=default,bg=#44475a'

# List of plugins
set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#h | #S"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
