unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

set -a terminal-features 'xterm-256color:RGB'
set -g base-index 1
set -g pane-base-index 1
set -g history-limit 50000
set -g mouse on
setw -g mode-keys vi

set -g @bg0 "#282a36"
set -g @bg1 "#44475a"
set -g @bg2 "#6272a4"
set -g @fg "#f8f8f2"
set -g @yellow "#f1fa8c"
set -g @green "#50fa7b"

set -g status-style "bg=#{@bg1}"
set -g window-status-separator ""

set -g status-left "#{?client_prefix,#[bg=#{@yellow}],#[bg=#{@green}]}#[fg=#{@bg0}] #H | #S #[fg=#{@bg1}]"
set -g status-left-length 100
set -g status-right '#[bg=#{@bg2},fg=#{@bg1}]#[fg=#{@fg}] #(TZ="America/Los_Angeles" date +"%%a %%b %%e %%l:%%M %%p") '
set -g status-right-length 100

set -g window-status-current-format "#[bg=#{@bg1},fg=#{@bg2}]#[bg=#{@bg2},fg=#{@fg}] #I: #W #[fg=#{@bg1}]"
set -g window-status-format " #I: #W "
set -g window-status-style "bg=#{@bg1},fg=#{@fg}"
